import smtplib
import os
import tempfile
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from email.utils import formatdate
from config import (
    SENDMAIL, SMTP_HOST, SMTP_PORT, SMTP_FROM, SMTP_TO, PDF_TITLE
)


def _build_html(meeting, agenda, decisions, pending, open_tasks):
    STATUS_LABEL = {
        'done': '✓ Closed', 'pending_next': '→ Deferred',
        'discussing': '~ Discussed', 'pending': '○ Not reviewed',
    }

    rows_agenda = ""
    for i, item in enumerate(agenda, 1):
        status = STATUS_LABEL.get(item['status'], item['status'])
        details = item.get('details') or ''
        author = item.get('added_by_name') or ''
        rows_agenda += f"<tr><td>{i}</td><td><b>{item['title']}</b><br><small>{details}</small></td><td>{status}</td><td>{author}</td></tr>"

    rows_decisions = ""
    for i, d in enumerate(decisions, 1):
        kind = "Done" if d['decision_type'] == 'done' else "ToDo"
        resp = d.get('responsible') or '—'
        rows_decisions += f"<tr><td>{i}</td><td>{d['text']}</td><td>{kind}</td><td>{resp}</td></tr>"

    rows_pending = ""
    for p in pending:
        note = p.get('note') or '—'
        resp = p.get('responsible') or '—'
        rows_pending += f"<tr><td>{p.get('agenda_title') or '—'}</td><td>{note}</td><td>{resp}</td></tr>"

    rows_tasks = ""
    for i, t in enumerate(open_tasks, 1):
        assignee = t.get('assignee') or '—'
        deadline = t.get('deadline') or '—'
        created = t.get('created_by_name') or '—'
        rows_tasks += f"<tr><td>{i}</td><td>{t['title']}</td><td>{assignee}</td><td>{deadline}</td><td>{created}</td></tr>"

    started = (meeting.get('started_at') or '')[:16]
    ended = (meeting.get('ended_at') or '')[:16]

    table_style = 'border-collapse:collapse;width:100%;margin-bottom:24px;'
    th_style = 'background:#3b8ad1;color:#fff;padding:8px 10px;text-align:left;font-size:13px;'
    td_style = 'padding:7px 10px;border-bottom:1px solid #e0e0e0;font-size:13px;vertical-align:top;'
    tr_even = 'background:#f5f9ff;'

    def table(headers, rows, even=True):
        ths = "".join(f'<th style="{th_style}">{h}</th>' for h in headers)
        if not rows:
            colspan = len(headers)
            rows = f'<tr><td colspan="{colspan}" style="{td_style}color:#999;font-style:italic;">—</td></tr>'
        return (f'<table style="{table_style}"><thead><tr>{ths}</tr></thead>'
                f'<tbody>{rows}</tbody></table>')

    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8">
<style>
  body {{ font-family: Arial, sans-serif; color: #222; max-width: 900px; margin: 0 auto; padding: 24px; }}
  h1 {{ color: #3b8ad1; border-bottom: 3px solid #3b8ad1; padding-bottom: 8px; }}
  h2 {{ color: #3b8ad1; margin-top: 32px; font-size: 16px; text-transform: uppercase; letter-spacing: 1px; }}
  .meta {{ color: #666; font-size: 13px; margin-bottom: 24px; }}
  .footer {{ color: #aaa; font-size: 11px; margin-top: 32px; border-top: 1px solid #eee; padding-top: 12px; }}
</style></head><body>
<h1>{PDF_TITLE}</h1>
<div class="meta">
  <b>Topic:</b> {meeting['title']}<br>
  <b>Start:</b> {started} &nbsp; <b>End:</b> {ended}
</div>

<h2>1. Agenda</h2>
{table(['#', 'Item', 'Status', 'Author'], rows_agenda)}

<h2>2. Decisions</h2>
{table(['#', 'Decision', 'Type', 'Responsible'], rows_decisions)}

{'<h2>3. Deferred</h2>' + table(['Agenda Item', 'Note', 'Responsible'], rows_pending) if pending else ''}

<h2>{'4' if pending else '3'}. Open Tasks</h2>
{table(['#', 'Task', 'Assignee', 'Deadline', 'Created by'], rows_tasks)}

<div class="footer">Auto-generated by Meeting Bot</div>
</body></html>"""
    return html


async def send_email_report(meeting, agenda, decisions, pending, open_tasks, pdf_path=None):
    """Send HTML email with optional PDF attachment. Non-blocking — logs errors silently."""
    if not SENDMAIL:
        return
    if not SMTP_HOST or not SMTP_TO:
        return

    recipients = [r.strip() for r in SMTP_TO.split(',') if r.strip()]
    if not recipients:
        return

    try:
        msg = MIMEMultipart('mixed')
        msg['From']    = SMTP_FROM
        msg['To']      = ', '.join(recipients)
        msg['Date']    = formatdate(localtime=True)
        msg['Subject'] = f"{PDF_TITLE}: {meeting['title']}"

        html = _build_html(meeting, agenda, decisions, pending, open_tasks)
        msg.attach(MIMEText(html, 'html', 'utf-8'))

        # Attach PDF if provided
        if pdf_path and os.path.isfile(pdf_path):
            with open(pdf_path, 'rb') as f:
                part = MIMEApplication(f.read(), Name=os.path.basename(pdf_path))
            part['Content-Disposition'] = f'attachment; filename="{os.path.basename(pdf_path)}"'
            msg.attach(part)

        server = smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=10)
        server.sendmail(SMTP_FROM, recipients, msg.as_bytes())
        server.quit()

    except Exception as e:
        import logging
        logging.getLogger(__name__).error(f"Email send failed: {e}")
